# Generated by Django 5.2.8 on 2025-11-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(max_length=200)),
                ('destination_city', models.CharField(max_length=200)),
                ('container_type', models.CharField(max_length=100)),
                ('transport_type', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('input_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-input_date'],
            },
        ),
    ]
