# Generated by Django 5.2.8 on 2025-11-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='last_edited_by',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='processing_status',
            field=models.CharField(choices=[('correct', 'Корректно'), ('incorrect', 'Некорректно'), ('pending', 'В обработке')], default='pending', max_length=20),
        ),
    ]
