# Generated by Django 5.2.8 on 2025-12-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_rate_last_edited_by_rate_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя клиента'),
        ),
    ]
