# Generated by Django 5.2.8 on 2025-12-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_rate_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('RUB', '₽')], default='USD', max_length=3, verbose_name='Валюта'),
        ),
    ]
