# Generated by Django 5.2.8 on 2025-12-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_rate_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='input_date',
            field=models.DateField(),
        ),
    ]
